parameters:
#    kunstmaan_admin.example.class: Kunstmaan\AdminBundle\Example

services:
#    kunstmaan_admin.example:
#        class: %kunstmaan_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


