parameters:
#    kunstmaan_k_admin.example.class: Kunstmaan\KAdminBundle\Example

services:
#    kunstmaan_k_admin.example:
#        class: %kunstmaan_k_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


