parameters:
#    kunstmaan_k_admin_list.example.class: Kunstmaan\KAdminListBundle\Example

services:
#    kunstmaan_k_admin_list.example:
#        class: %kunstmaan_k_admin_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]



  adminlist.factory:
        class: Kunstmaan\KAdminListBundle\AdminList\AdminListFactory

  adminlist.twig.extension:
        class: Kunstmaan\KAdminListBundle\AdminList\AdminListTwigExtension
        tags:
            -  { name: twig.extension }