 
KunstmaanMediaBundle:
    resource: "@KunstmaanMediaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%

KunstmaanAdminBundle:
    resource: "@KunstmaanAdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
    
KunstmaanPagePartBundle:
    resource: "@KunstmaanPagePartBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
    
KunstmaanViewBundle_searchpage:
    resource: "@KunstmaanViewBundle/Controller/SearchPageController.php"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
        
KunstmaanFormBundle:
    resource: "@KunstmaanFormBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
        
KunstmaanViewBundle_slug:
    resource: "@KunstmaanViewBundle/Controller/SlugController.php"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
        
KunstmaanDemoBundle_default:
    resource: "@KunstmaanDemoBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    
