parameters:
#    kunstmaan_demo.example.class: Kunstmaan\DemoBundle\Example

services:
    kunstmaan_admin.menu_builder:
        class: Kunstmaan\AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@translator", [@kunstmaan_media.media_menu]]

    kunstmaan_admin.pageparts_builder:
        class: Kunstmaan\DemoBundle\PagePartAdmin\PagePartAdminConfigurator
        arguments: [[@kunstmaan_media.pageparts, @kunstmaan_pagepart.pageparts]]