parameters:
#    kunstmaan_k_admin_node.example.class: Kunstmaan\KAdminNodeBundle\Example

services:
#    kunstmaan_k_admin_node.example:
#        class: %kunstmaan_k_admin_node.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
       node.listener:
         class: Kunstmaan\KAdminNodeBundle\Listener\NodeGenerator
         tags:
                - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }
                - { name: doctrine.event_listener, event: postPersist, method: postPersist }
                - { name: doctrine.event_listener, event: prePersist, method: prePersist }
