services:
    kunstmaansandboxdemobundle.default_locale_listener:
        class: Kunstmaan\SandboxDemoBundle\EventListener\DefaultLocaleListener
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: [%defaultlocale%]
